version: "2"
services:
  nginx-react:
    container_name: ngixreactapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:80
    environment:
      NODE_ENV: production

  backend:
    build: ./BE
    command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000
