version: "3"
services:
  frontend:
    build: ./FE
    ports:
      - 8088:80
    environment:
      NODE_ENV: production

  backend:
    build: ./BE
    ports:
      - 8000:8000
    environment:
      - ENV=dev
    links:
      - database
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8000
    depends_on:
      - database
    

  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    expose:
     - "5432"
    environment:
      POSTGRES_PASSWORD: password

  datadog:
    image: gcr.io/datadoghq/agent:7
    pid: host
    environment:
     - DD_SITE=datadoghq.com
     - DD_LOGS_ENABLED=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
     - /var/lib/docker/containers:/var/lib/docker/containers:ro
networks:
  default: