version: "2"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:80
    environment:
      NODE_ENV: production

  backend:
    build: ./BE
    command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  